### ISSUE TITLE
Installation error help～

### ISSUE THREAD

**Issue by jaymrx** [seikan/homebridge-mi-air-purifier#10]
^Cpi@raspberrypi:~ $ npm install -g homebridge-mi-air-purifier miio
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
/usr/lib
├── homebridge-mi-air-purifier@1.1.0 
└─┬ miio@0.13.0 
  ├── appdirectory@0.1.0 
  ├─┬ chalk@1.1.3 
  │ ├── ansi-styles@2.2.1 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.1.1 
  │ ├── strip-ansi@3.0.1 
  │ └── supports-color@2.0.0 
  ├─┬ debug@2.6.8 
  │ └── ms@2.0.0 
  ├── minimist@1.2.0 
  └─┬ mkdirp@0.5.1 
    └── minimist@0.0.8 

npm ERR! Linux 4.9.35-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "homebridge-mi-air-purifier" "miio"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.npm/_logs/2017-07-11T15_34_58_430Z-debug.log
pi@raspberrypi:~ $

**Comment by Brklnbnc** [comment]
Try again as root: 
sudo npm install -g homebridge-mi-air-purifier miio

**Comment by seikan** [comment]
@jaymrx Have you resolved you issue?

**Comment by jaymrx** [comment]
THX~~ @Brklnbnc 

```
pi@raspberrypi:~ $ sudo npm install -g homebridge-mi-air-purifier miio
/usr/bin/miio -> /usr/lib/node_modules/miio/cli/index.js
/usr/lib
├── homebridge-mi-air-purifier@1.1.0 
└─┬ miio@0.13.0 
  ├── appdirectory@0.1.0 
  ├─┬ chalk@1.1.3 
  │ ├── ansi-styles@2.2.1 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.1.1 
  │ ├── strip-ansi@3.0.1 
  │ └── supports-color@2.0.0 
  ├─┬ debug@2.6.8 
  │ └── ms@2.0.0 
  ├── minimist@1.2.0 
  └─┬ mkdirp@0.5.1 
    └── minimist@0.0.8 

pi@raspberrypi:~ $ 
```
@seikan Very good plug-in～
