### ISSUE TITLE
ambience light sensor

### ISSUE THREAD

**Issue by andriuskr** [seikan/homebridge-mi-air-purifier#11]
Air purifier for night mode detection has ambient light sensor. Maybe there is possibility to expose this sensor to homekit ? apple home app supports ambient light sensor (for example Philips hue motion light sensor can bee seen in home app).

**Comment by seikan** [comment]
I will look into this. Thanks.

**Comment by seikan** [comment]
My version of device is not supported. I will added this when I got the new generation Air purifier.
