### ISSUE TITLE
HomeKit and Homebridge support new Air Purifier service in iOS11

### ISSUE THREAD

**Issue by CyrusSUEN** [seikan/homebridge-mi-air-purifier#16]
Could you add a new branch that make use of the [new air purifier type](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L2467-L2484) for iOS11 HomeKit? 

Or can you think of a better way to deal with the problem (for users running iOS10 which doesn't support air purifier and users for iOS11)? 

I'm thinking that maybe we could add `config.isIOS11` in the config file to determine that. Or does Homebridge provides an API to check the iOS version?

**Comment by abcabcabcab** [comment]
https://github.com/YinHangCode/homebridge-mi-airpurifier

**Comment by seikan** [comment]
iOS 11 is supported now.
