### ISSUE TITLE
Support second generation?

### ISSUE THREAD

**Issue by vmstudio2016** [seikan/homebridge-mi-air-purifier#17]
Support second generation?

**Comment by seikan** [comment]
Hi, it should be supported, can you please try with latest version and let me know?

**Comment by SirNoble** [comment]
Anyone worked out if it works?

**Comment by ayman** [comment]
I just set it up on a Mi Air Purifier 2 - works great!

**Comment by red3** [comment]
@ayman Do I need to buy a XiaoMi gateway to work with the homebridge server? or just the Mi Air Purifier 2 is enough.

**Comment by ayman** [comment]
I just have the Mi Air 2 and followed the instructions in the `README.md` - gateway not needed.

**Comment by jerzytraczynski** [comment]
Hey, can anyone confirm that it will work with Xiaomi Air Purifier 2S (upgarded version of the one you’ve asked)?

**Comment by robhester** [comment]
> Hey, can anyone confirm that it will work with Xiaomi Air Purifier 2S (upgarded version of the one you’ve asked)?

I can't get the 2S to work. Did it work for you?

**Comment by jerzytraczynski** [comment]
Yes, that's it.   
  
  
  
  
  
 Jerzy Traczyński     
  

  
  
>
