### ISSUE TITLE
will this work if firewall is set to only allow purifier to communicate on local network?

### ISSUE THREAD

**Issue by czyz** [seikan/homebridge-mi-air-purifier#19]
For security reasons I like to wall off my internet-of-things devices from the internet and control them over the local network. Do you know if your software can be used with a xiaomi purifier that only has LAN but not WAN access - or maybe does the xiaomi purifier need to "phone home" to servers in China in order to function?

Thanks for any information.

On a different note - it appears there's a [similar-looking homebridge plugin for the xiaomi purifiers](https://github.com/YinHangCode/homebridge-mi-airpurifier). I'm not sure how it differs from this one.

**Comment by seikan** [comment]
Yes, it's working within same LAN without WAN connections.
