### ISSUE TITLE
When add homebridge to Apple's home kit, it stops running.

### ISSUE THREAD

**Issue by suhyeoni** [seikan/homebridge-mi-air-purifier#2]
It came out that I was waiting too.
Thank you very much.

I will add homebridge from Apple's homekit.

Other sensors are well registered.

However, when you add the Xiaomi Mi Air Sensor, Homebridge will stop running with the same error as the following screenshot.

https://www.dropbox.com/s/wb0czpg9itxsbew/error.png?dl=0

**Comment by seikan** [comment]
This error has been resolved in version [1.1.0](https://github.com/seikan/homebridge-mi-air-purifier/releases/tag/1.1.0).
