### ISSUE TITLE
Works but status will get stuck on turning on

### ISSUE THREAD

**Issue by Tom-Shen** [seikan/homebridge-mi-air-purifier#20]
I am using this with my Mi Air Purifier 2. It works perfectly except a small bug where the status will get stuck on turning on or turning off. Restarting the Home app will make it return to normal. Happening on iOS 11, any ideas on this? Thanks.

**Comment by seikan** [comment]
It's a bug from miio. Please update your miio to latest version.

**Comment by bazingaterry** [comment]
Still get stuck after I update to the latest version of miio and homebridge.
