### ISSUE TITLE
请问设置空气净化器转速对应的中文siri指令是什么?

### ISSUE THREAD

**Issue by detecti1** [seikan/homebridge-mi-air-purifier#22]
> Notes: Alternatively, you can ask Siri to change the fan speed within the range to adjust the air purifier mode. Example:
>
> Hey Siri, change the air purifier speed to 100.

多谢 :)

**Comment by seikan** [comment]
可以参考这里：
http://www.feng.com/apple/news/2015-06-25/Apple-announced-HomeKit-Siri-instructions-enough-daily-life_617305.shtml
