### ISSUE TITLE
typo in example config

### ISSUE THREAD

**Issue by phenomeus** [seikan/homebridge-mi-air-purifier#24]
not a dot, there must be a comma  

"accessories": [
    {
      "accessory": "MiAirPurifier",
      "name": "Air Purifier",
      "ip": "ADDRESS_OF_THE_AIR_PURIFIER",
      "token": "TOKEN_FROM_STEP_3"**,**
      "showTemperature": true,
      "showHumidity": true,
      "showAirQuality": true
    }
  ]

**Comment by seikan** [comment]
Thanks for reporting.
