### ISSUE TITLE
Add miio as dependency in package.json

### ISSUE THREAD

**Issue by aholstenson** [seikan/homebridge-mi-air-purifier#33]
First, thanks for using miio to build something awesome! I recently released version 0.15.x of miio which introduces several incompatible changes. The API in miio is slowly becoming more stable but until we reach 1.0.0 there are going to be breaking changes in some releases.

It would be great if you could update your Homebridge-plugin to use miio as a local dependency instead of a global dependency.  That way installing your plugin will automatically install the version of miio needed. The easiest way to do this is to use `npm install` in your project and to set the version to 0.14.1:

```
npm install --save miio@0.14.1
```

That way your users and you will get version 0.14.1 until you are ready to update your plugin to the new API available in 0.15.x.

**Comment by phenomeus** [comment]
upvote! absolutely necessary. caused me some headaches right now, but now its downgraded and running again. so please :) update, that would help

**Comment by seikan** [comment]
Thanks, it was unexpected that miio changed the function name in 0.15.
