### ISSUE TITLE
This plugin works with Xiaomi Mi Air Purifier 2?

### ISSUE THREAD

**Issue by norbertcala** [seikan/homebridge-mi-air-purifier#34]
This plugin works with Xiaomi Mi Air Purifier 2?

**Comment by jerzytraczynski** [comment]
Tak, działa: https://github.com/seikan/homebridge-mi-air-purifier/issues/17

**Comment by norbertcala** [comment]
A Wiesz jak dodać dwa?

**Comment by jerzytraczynski** [comment]
Nie wiem - nie mam żadnego. Tu jest taki Pull Request: https://github.com/seikan/homebridge-mi-air-purifier/pull/12
Chcę zaopatrzyć się na razie w jeden 2s (czekam aż będą w polskiej dystrybucji w lepszej cenie), ale jak uda Ci się podłączyć oba AP2 to napisz.

**Comment by leoneleone** [comment]
yes it does. please close this issue.

**Comment by seikan** [comment]
Tested and worked with AP2.
