### ISSUE TITLE
Error device is not a constructor

### ISSUE THREAD

**Issue by consoleman** [seikan/homebridge-mi-air-purifier#37]
Hi,
Can’t get the plugin running.
I get Error:miio device is not a constructor at MiAirPurifier.discover.

Can anyone please help?

**Comment by kondratk** [comment]
Got same issue with node 8.9.1 on macOS 10.13.2 and latest homebridge.

**Comment by consoleman** [comment]
Solved the problem with downgraded miio version

**Comment by leoneleone** [comment]
@consoleman 

which miio version did you downgrade to?

**Comment by consoleman** [comment]
npm install -g miio@0.14.1 works for me

**Comment by leoneleone** [comment]
[](https://github.com/aholstenson/miio/issues/102)

**Comment by kondratk** [comment]
I've created pull request with fix of this error. Now purifier plugin should work with latest mioo.
Check PR: #39

CC: @consoleman
