### ISSUE TITLE
Version 1.2.2 Night Mode/ Automatic Mode 

### ISSUE THREAD

**Issue by Partyboy97** [seikan/homebridge-mi-air-purifier#41]
Hi, 

how can I activate the night mode with version 1.2.2? If the mode is set to manual, 5-7qm is the minimum value to set. The automatic mode does not always work, even if it is set automatically via HomeKit it runs in manual mode.

**Comment by leoneleone** [comment]
@seikan I believe that the Rotation Speed characteristic should be reverted back to the old functionality (Auto-Silent-Favourite). The “Favourite” fan setting on the Mi AirPurifier is normally set only once to determine the size of the room the purifier is placed in. I don’t really see the need to be able to change this via HomeKit because it’s unlikely that people would move the airpurifier to different room on a regular basis. 

The previous (original) Fan Speed functionally was much better in my opinion.

**Comment by Partyboy97** [comment]
Is it possible to add a mode under Details? automatic - manual - silent? Or are the fields specified by HomeKit?

**Comment by leoneleone** [comment]
@Partyboy97 

That isn't possible according the HomeKit protocol 😔

**Comment by Partyboy97** [comment]
@leoneleone the previous solution was good.

can the HomeKit protocol differentiate the fan speed in Auto and Manual modes? if so you could in auto mode <= 20% Night >= 21% Automatic. If not, I would like to say the previous solution.

**Comment by leoneleone** [comment]
@Partyboy97 Unfortunately not. The existing options under "details" are the only parameters which HomeKit is expecting from an Air Purifier device. You can have either Manual or Auto. "Night mode" is not something that HomeKit understands just yet.

Do you find setting/changing the "Favourite Level" useful at all? I have the Favourite Level on all my Purifiers fixed, I never change it.

**Comment by leoneleone** [comment]
/**
 * Characteristic "Target Air Purifier State"
 */

Characteristic.TargetAirPurifierState = function() {
  Characteristic.call(this, 'Target Air Purifier State', '000000A8-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.UINT8,
    maxValue: 1,
    minValue: 0,
    validValues: [0,1],
    perms: [Characteristic.Perms.READ, Characteristic.Perms.WRITE, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};

inherits(Characteristic.TargetAirPurifierState, Characteristic);

Characteristic.TargetAirPurifierState.UUID = '000000A8-0000-1000-8000-0026BB765291';

// The value property of TargetAirPurifierState must be one of the following:
Characteristic.TargetAirPurifierState.MANUAL = 0;
Characteristic.TargetAirPurifierState.AUTO = 1;

**Comment by Partyboy97** [comment]
@leoneleone not really. I use 3 scenes for the 4 air purifiers. Automatically when I'm not at home. Favorite when I'm at home and the air is bad. Otherwise quiet in night mode if the air quality value is good.

**Comment by leoneleone** [comment]
the Air Purifier will change to Favourite automatically if the air quality is bad. You can see details of setting that in the Mi app. Changing the Favourite Level via the HomeKit Fan Speed is absolutely useless to me to be honest. Feel free to use my fork of this plugin. It's basically all the same except that Fan Speed controls (0= off, 20<= auto, 60<= silent, 80<=favourite)

https://github.com/leoneleone/homebridge-mi-air-purifier
*make sure you use the "master" branch of the fork.

if you want a 'Silent' option but you want the current Fan Speed implementation to remain the same (controlling Favourite Level, the only way to do that is to create a Switch Service which controls Silent/SleepMode on/off, but this would produce another tile in the Home.app for that Silent Switch, not the ideal for me.

**Comment by leoneleone** [comment]
I leave my purifiers on Auto all the time, I think the Auto setting is already quiet enough for me. Only have it set to Sleep when I go to bed, and I turn the LED/Display off as well.

**Comment by Partyboy97** [comment]
@leoneleone the mi app does not change any mode automatically. Maybe that's how you configured it for you in the mi app. The automatic mode is silent only as long as you do not smoke in your apartment. Then the fan goes to 100% for 5-10 minutes. I prefer the favorite mode for 15-20 minutes and can still watch TV.

**Comment by leoneleone** [comment]
@Partyboy97  My mistake, the Mi app doesn’t give you that option. All the same, that is the Auto mode functionality, it’s sets the purifier to “favourite” if the air quality reading is high and then returns back to Auto when the air quality is good again. 

I’m a smoker but I don’t smoke inside my apartment. I would only smoke outdoors 😉

**Comment by Partyboy97** [comment]
@leoneleone  https://github.com/leoneleone/homebridge-mi-air-purifier
*make sure you use the "master" branch of the fork.

/usr/local/lib/node_modules/homebridge-mi-air-purifier/index.js:76
        this.lightBulbService = new Service.LightBulb(this.name + "DISPLAY");
                                ^

TypeError: Service.LightBulb is not a constructor
    at MiAirPurifier (/usr/local/lib/node_modules/homebridge-mi-air-purifier/index.js:76:26)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:275:29)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by Partyboy97** [comment]
I'm back @1.2.1 with miio 14.1 as dependency 

@seikan please add the old Fan Speed controls (0= off, 20<= auto, 60<= silent, 80<=favourite)
