### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by consoleman** [seikan/homebridge-mi-air-purifier#42]
I changed nothing but instantly there ist an error and the plug in does not work any more.

node_modules/homebridge-mi-air-purifier/index.js:199:15)
TypeError: Cannot read property 'call' of undefined
		            ^
		this.device.call('get_prop', ['favorite_level'])
/usr/local/lib/node_modules/homebridge-mi-air-purifier/index.js:199

Any help please?

**Comment by seikan** [comment]
Can you please try with latest version?
