### ISSUE TITLE
Cant find my Mi Air purifier 2

### ISSUE THREAD

**Issue by John88a** [seikan/homebridge-mi-air-purifier#47]
HI, i follow the instructions, installed the plugin, but while running home bridge, i type the command:

miio --discover --sync

and the only thing that shows up after a few minutes its my broadlink RM Pro, nothing else ...

Homebridge Server is running on the same network as the Air purifier, what am i doing wrong?

thanks

**Comment by seikan** [comment]
Are you still having discovery issue? Make sure you have updated your firmware to latest version.
