### ISSUE TITLE
In apple homekit, the state of air purifier is no response.

### ISSUE THREAD

**Issue by suhyeoni** [seikan/homebridge-mi-air-purifier#5]
Quick update Thank you very much.

In apple homekit App, the state of air purifier is no response.

Air quality, humidity and temperature are also unknown.

**Comment by seikan** [comment]
Hi, please wait a while, then it will get updated automatically.

Please let me know if the problem still persist.

**Comment by suhyeoni** [comment]
Waiting 10 minutes is no response.

I have Mi Air Air Purifier 2.

The firmware is the latest version, 1.2.4_59.

The error code is as follows.
--------------------------------------------------------------------------------
type: 'air-purifier',                                                                                                     
  model: 'zhimi.airpurifier.m1',                                                                                            
  writeOnly: true } undefined                                                                                               
(node:90) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '
model' of undefined                                                                                                         
(node:90) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not ha
ndled will terminate the Node.js process with a non-zero exit code.

**Comment by seikan** [comment]
Do you have multiple device or just one?

**Comment by suhyeoni** [comment]
Mi Air Air Purifier is one.

Mi Gateway V2 and Mi Smart Plug are also available.

**Comment by seikan** [comment]
I'm not sure is the problem from v2 gateway as it has limited space. I will investigate.

**Comment by suhyeoni** [comment]
homebridge-miio and homebridge-mijia were removed.

Only homebridge-mi-air-purifier miio are installed, but Mi Air is still No Responsive.

**Comment by suhyeoni** [comment]
It was a collision problem with homebridge-miio.

Delete homebridge-miio and try again. Thank you very much.
