### ISSUE TITLE
Failed to discover Mi Air Purifier at 192.168.1.123

### ISSUE THREAD

**Issue by kurokiji** [seikan/homebridge-mi-air-purifier#67]
Hi!

I have this error:
Failed to discover Mi Air Purifier at 192.168.1.123

I pick up the token from the old android version of the Mi Home App. 
Also, I checked it on the plugin.ini file.
So, I think my token is right.

I did a fresh install of homebridge several times, but have the issue every time.

What can I do now? 

Thanks!

**Comment by rubentavares** [comment]
This solved it for me:

install plugin with @1.2.2
npm install -g homebridge-mi-air-purifier@1.2.2

**Comment by fluidof** [comment]
It works for me downgrading @1.2.2- So that it's impossible to use the latest version?

**Comment by fuomag9** [comment]
> 
> 
> It works for me downgrading @1.2.2- So that it's impossible to use the latest version?

It seems so
