### ISSUE TITLE
Air Purifier - Unresponsive.

### ISSUE THREAD

**Issue by iCatalystic** [seikan/homebridge-mi-air-purifier#8]
Hi There.

Upon the initial install + launch of HomeBridge, says it's running.
But when i go to HomeKit the Air Purifier is unresponsive and not able to be controlled at all.

Running iOS 10.1.1 (JailBroken) not sure if this matters considering the iOS version i'm running.

Not sure what else to do, all the accessories and temperature etc shows up - just not responsive.

Cheers.

**Comment by Deteorek** [comment]
Hi

I had the same thing but uninstall **npm uninstall -g homebridge-mi-air-purifier miio** and than install again + restart my Raspberry Pi did the trick. It looks like something to do with **miio**

Cheers

**Comment by seikan** [comment]
@Deteorek Thanks for clarify this issue. Yes, it was a problem with latest Xiaomi firmware with miio.
